# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zIQb2DWozL76NvFVKN29oBbF7PSHixuy
"""

!pip install chatterbot

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

from spacy.cli import download

download("en_core_web_sm")

class ENGSM:
    ISO_639_1 = 'en_core_web_sm'

chatbot = ChatBot("BotHenrique", tagger_language=ENGSM)

chat = [
    "Salve",
    "E aí, suave?",
    "De boa",
    "Qual a boa de hoje?",
    "a Hashtag tá ensinando Python e até chatbot",
    "Ai sim",
    "Daora né",
    "É",
]

trainer = ListTrainer(chatbot)
trainer.train(chat)

while True:
    user_input = input("Mande uma mensagem para o chatbot:")
    if user_input == "parar":
        break
    resp = chatbot.get_response(user_input)
    print(resp)

# Reiniciar a base de dados
chatbot.storage.drop()